pipeline {
  agent any


  environment {
    TF_VAR_FILE = 'options.tfvars'
    CERT_SCRIPT = './generate_certs.sh'
  }

  stages {
    stage('Generate Self-Signed Cert') {
      when {
        expression { params.Options == 'Deploy' || params.Options == 'Destroy' }
      }
      steps {
        sh '''
          chmod +x ${CERT_SCRIPT}
          ${CERT_SCRIPT}
        '''
      }
    }

    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }

    stage('Terraform Plan') {
      when {
        expression { params.Options == 'Deploy' }
      }
      steps {
        sh 'terraform plan -var-file=${TF_VAR_FILE} -out=tfplan'
      }
    }

    stage('Terraform Apply') {
      when {
        expression { params.Options == 'Deploy' }
      }
      steps {
        sh 'terraform apply -auto-approve tfplan'
      }
    }

    stage('Terraform Destroy') {
      when {
        expression { params.Options == 'Destroy' }
      }
      steps {
        sh 'terraform destroy -var-file=${TF_VAR_FILE} -auto-approve'
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
